### ISSUE TITLE
How to reconfigure fail on console feature ?

### ISSUE THREAD

**Issue by kopax-polyconseil** [Codecademy/console-fail-test#61]
I have the following in `setupTests.js`:

```jsx
const allowConsoleDefaultConfig = {
  debug: true,
  error: true,
  log: true,
  warn: true,
}

global.allowConsole = function (config = allowConsoleDefaultConfig) {
  const { debug, error, log, warn } = { ...allowConsoleDefaultConfig, ...config }
  consoleFailTestModule.cft({
    testFramework: 'jest',
    spyLibrary: 'jest',
    console: {
      debug,
      error,
      log,
      warn,
    },
  })
}

global.allowConsole({
  debug: false,
  error: false,
  log: false,
  warn: false,
})
```

Within a test, I run at the top of the file : 

```js
allowConsole()
```

I expect the test to allow console logging. 

Instead, I have the initial configuration and my test fail.

How can I reconfigure the fail on console feature ?

**Comment by JoshuaKGoldberg** [comment]
Hey @kopax-polyconseil, thanks for posting an issue!

It's hard to see what's going on from just the same code. Could you post a link to a full repository, such as a GitHub repo or Codesandbox, that I could take a look at?

**Comment by kopax-polyconseil** [comment]
Hi and thanks for the quick reply @JoshuaKGoldberg , of course this is the project: https://github.com/pass-culture/pass-culture-app-native/tree/allow-console


This is the [`setupTest.js`](https://github.com/pass-culture/pass-culture-app-native/blob/allow-console/src/tests/setupTests.js)


```bash
git clone git@github.com-work:pass-culture/pass-culture-app-native.git
cd pass-culture-app-native
git checkout allow-console
yarn
yarn run test:unit
```

Then open [`github.com/pass-culture/pass-culture-app-native/src/features/profile/pages/NotificationSettings.test.tsx`](https://github.com/pass-culture/pass-culture-app-native/blob/allow-console/src/features/profile/pages/NotificationSettings.test.tsx#L23)

**Comment by kopax-polyconseil** [comment]
I've updated the branch with the right code (cause it was wip when I pushed the first time).

I also added a console.log if you run that particular test, you'll see : 

```
  console.log
    { debug: false, error: false, log: false, warn: false }

      at allowConsole (src/tests/setupTests.js:20:11)

  console.log
    { debug: true, error: true, log: true, warn: true }

      at allowConsole (src/tests/setupTests.js:20:11)
```

This means we call in order:

```jsx
consoleFailTestModule.cft({
    testFramework: 'jest',
    spyLibrary: 'jest',
    console: {
      debug: false,
      error: false,
      log: false,
      warn: false,
    },
})
consoleFailTestModule.cft({
    testFramework: 'jest',
    spyLibrary: 'jest',
    console: {
      debug: true,
      error: true,
      log: true,
      warn: true,
    },
})
```

And the end result is the configuration from the first line.

**Comment by kopax-polyconseil** [comment]
Sorry it was my default configuration which was reverted ^^, thanks still for being around and watching our back :)

**Comment by JoshuaKGoldberg** [comment]
😄 , glad it's all working out! And thanks for using console-fail-test!
